apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.service.otlpGrpcPort }}
      targetPort: otlp-grpc
    - name: otlp-http
      port: {{ .Values.service.otlpHttpPort }}
      targetPort: otlp-http
    - name: prometheus
      port: {{ .Values.service.prometheusPort }}
      targetPort: prometheus
