apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: proxy
    - name: status
      port: {{ .Values.service.statusPort }}
      targetPort: status
