apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - {name: Mimir, uid: mimir, type: prometheus, access: proxy, url: {{ .Values.datasources.mimirUrl }}, isDefault: true}
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: {{ .Values.datasources.tempoUrl }}
        jsonData:
          tracesToLogs: {datasourceUid: loki}
          tracesToMetrics: {datasourceUid: mimir}
          serviceMap: {datasourceUid: mimir}
      - {name: Loki, uid: loki, type: loki, access: proxy, url: {{ .Values.datasources.lokiUrl }}}
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: customer-msa
        folder: Customer MSA
        type: file
        options:
          path: /var/lib/grafana/dashboards
  customer-msa-overview.json: |
    {{- .Files.Get "files/customer-msa-overview.json" | nindent 4 }}
