apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - {name: Prometheus, uid: prometheus, type: prometheus, access: proxy, url: {{ .Values.datasources.prometheusUrl }}, isDefault: true}
      - {name: Jaeger, uid: jaeger, type: jaeger, access: proxy, url: {{ .Values.datasources.jaegerUrl }}}
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: customer-msa
        folder: Customer MSA
        type: file
        options:
          path: /var/lib/grafana/dashboards
  customer-msa-overview.json: |
    {{- .Files.Get "files/customer-msa-overview.json" | nindent 4 }}
