apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.admin.username | quote }}
  admin-password: {{ .Values.admin.password | quote }}
