apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  tempo.yaml: |
    # Grafana Tempo in monolithic (single-binary) mode with local filesystem storage (demo only).
    multitenancy_enabled: false
    stream_over_http_enabled: true
    server:
      http_listen_port: 3200
      log_level: error
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
    storage:
      trace:
        backend: local
        wal:
          path: /tmp/tempo/wal
        local:
          path: /tmp/tempo/blocks
        block:
          bloom_filter_false_positive: 0.05
          index_downsample_bytes: 1000
          encoding: zstd
        search:
          encoding: snappy
        block_retention: {{ .Values.retention }}
    compactor:
      compaction:
        block_retention: {{ .Values.retention }}
    usage_report:
      reporting_enabled: false
